name: Github Actions - Workflow run Basic Template
run-name: Running - Workflow run Basic Template
on:
    workflow_run:
        workflows: [trigger 1]
jobs:
    on-push: 
        runs-on: ubuntu-latest
        steps:
            - name: Coment√°rio
              run: |
                echo "Workflow que foi trigado"