name: Github Actions - Cron Job Template
run-name: Running - ${{ github.event_name }}
on:
  schedule:
   # 9 horas da manhã de segunda a sexta
      - cron: '0 12 * * 1-5'
      #Minuto 2 e minuto 10 as 8 horas da manhã e 10 horas da manhã    
      - cron: '2,10 11,13 * * *'
jobs:
    on-worflow_dispatch:
        runs-on: ubuntu-latest
        steps:
            - name: Comentário
              run: |
                echo "Comentário Cron job"
