name: GitHub Actions - Worflow dispatch
run-name: Running - ${{ github.event_name }}
on:
  workflow_dispatch:
    inputs:
      browsers:
        description: Selecione um navegador
        type: string # literalmente uma string, forma mais livre de escrever, menos controle.
        default: chrome #não faz muito sentido usar com string, unica coisa que faz é já deixar escrito
        required: true # esse funciona bem não permitindo rodar sem digitar nada. mas ainda é vago.
jobs:
  on-workflow_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name:
        run: |
          echo "Comentário Worflow dispatch - ${{ inputs.browsers }}"