name: Github Actions - Push General
run-name: Running - ${{ github.event_name }}
on:
  push: #Condicionais para o gatilho:
    branches: #em alguma das branches descritas &
      - master
      - develop
    paths: #edições em arquivos com extensão .txt
      - '**.txt'
jobs:
  on-push:
  runs-on: ubuntu-20.04
  steps:
    - name: Comentário
      run: |
        echo "Comentário PUSH WORKFLOW"